### ISSUE TITLE
Self Managed Stack Set Deployment Support

### ISSUE THREAD

**Issue by linsona** [aws/aws-cdk-rfcs#332] opened 2021-06-08 17:09 UTC
## Description
Using CDK, we would like to define a template through CDK constructs and deploy as a Self Managed CFN Stack Set. 

Related: https://github.com/aws/aws-cdk-rfcs/issues/66

## Working Backwards
* User defines stack set the same way as normal cdk stack
* When user executes `cdk deploy` it would create a stack set if it does not exist or update an existing stack set + existing stack set instances.

Proposed Scope:
* Create New **Self Managed** Stack Set
  * https://docs.aws.amazon.com/AWSCloudFormation/latest/APIReference/API_CreateStackSet.html 
* Update Existing **Self Managed** Stack Set
  * Update includes updating existing Stack Set instances as well
  * https://docs.aws.amazon.com/AWSCloudFormation/latest/APIReference/API_UpdateStackSet.html
  * https://docs.aws.amazon.com/AWSCloudFormation/latest/APIReference/API_UpdateStackInstances.html
* Ability to set stack set configuration/deployment properties
  * Administration Role, Execution Role, Fault Tolerance, Concurrency, etc. 

Out of Scope (May be iteratively added in future):
* Service Managed Stack Set
* Add/Remove stack set instances by Id or OU

## Roles
* **Driver**: @linsona
* **Approver(s)**: (assigned by CDK team)

**Comment by eladb** [comment] 2021-06-08 17:11
@linsona can you please check if this might be a duplicate of #66 ?

**Comment by skinny85** [comment] 2021-06-10 20:53
@eladb it is not, because not all features of StackSets are included in this one (see the "Out of scope" section in https://github.com/aws/aws-cdk-rfcs/issues/332#issue-915265333).

**Comment by eladb** [comment] 2021-07-07 11:47
> @eladb it is not, because not all features of StackSets are included in this one (see the "Out of scope" section in #332 (comment)).

It's okay that we don't implement all the features immediately. I still think it's the same RFC.

Closing as dup so we can preserve the history and discussions around StackSets in a single place.

**Closed by eladb** 2021-07-07 11:47 UTC
Labels: management/tracking, status/proposed
