### ISSUE TITLE
Cost calculator

### ISSUE THREAD

**Issue by eladb** [aws/aws-cdk-rfcs#22] opened 2019-12-08 22:40 UTC
|PR|Champion|
|--|--------|
|# |        |

## Description

https://github.com/aws/cdk-ops/issues/411

## Progress

- [x] Tracking Issue Created
- [ ] RFC PR Created 
- [ ] Core Team Member Assigned 
- [ ] Initial Approval / Final Comment Period
- [ ] Ready For Implementation
    
    - [ ] implementation issue 1
- [ ] Resolved

**Comment by gabrielenosso** [comment] 2022-07-15 13:21
Looks like duplicate of Number 70 (or viceversa :)

**Comment by evgenyka** [comment] 2023-08-10 08:14
Closed as duplicate of https://github.com/aws/aws-cdk-rfcs/issues/70

**Closed by evgenyka** 2023-08-10 08:14 UTC
Labels: tools, internal
