### ISSUE TITLE
Add Sagemaker endpoint L2 construct

### ISSUE THREAD

**Issue by unavailablealfaa** [aws/aws-cdk-rfcs#441] opened 2022-06-30 19:37 UTC
## Description
SageMaker endpoint is the resource used to deploy and host models. It is created with the endpoint configuration provided in the request. This change is to introduce the Sagemaker endpoint L2 construct, which allows clients to define an endpoint with few lines of code. The amount of effort needed to create these resources is about the same as doing it using the AWS console.

#### Basic definition
In order to define am Endpoint, you must provide the name of an endpoint config. This following codes allow you to define a basic AWS Sagemaker Endpoints:
```ts
const endpoint = new sagemaker.Endpoint(this, 'MyEndpoint', {
  endpointName: 'MyEndpoint',
  endpointConfigName: 'MyEndpointConfig',
});
```

#### Applying tags to endpoints
You can apply [tags](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-resource-tags.html) to endpoint resources, example codes: 
```ts
new sagemaker.Endpoint(this, 'MyEndpoint', {
  endpointName: 'MyEndpoint',
  endpointConfigName: 'MyEndpointConfig',
  tags: {
    'key1': 'value1',
    'key2': 'value2',
  },
});
```
### Additional notes
The construct for Endpoint Configuration will be implemented in a separate change.
The other properties of Endpoint will be add incrementally in separate changes.

## Roles

| Role                | User
|---------------------|------------------------------
| Proposed by         | @unavailablealfaa
| Author(s)           | @unavailablealfaa, @SeekerWing
| API Bar Raiser      | @alias
| Stakeholders        | @alias, @alias, @alias

> See [RFC Process](https://github.com/aws/aws-cdk-rfcs#rfc-process) for details

## Workflow

- [x] Tracking issue created (label: `status/proposed`)
- [ ] API bar raiser assigned (ping us at [#aws-cdk-rfcs](https://cdk-dev.slack.com/archives/C025ZFGMUCD) if needed)
- [ ] Kick off meeting
- [ ] RFC pull request submitted (label: `status/review`)
- [ ] Community reach out (via Slack and/or Twitter)
- [ ] API signed-off (label `api-approved` applied to pull request)
- [ ] Final comments period (label: `status/final-comments-period`)
- [ ] Approved and merged (label: `status/approved`)
- [ ] Execution plan submitted (label: `status/planning`)
- [ ] Plan approved and merged (label: `status/implementing`)
- [ ] Implementation complete (label: `status/done`)

---

> Author is responsible to progress the RFC according to this checklist, and
apply the relevant labels to this issue so that the RFC table in README gets
updated.

**Comment by kaizencc** [comment] 2022-07-22 15:27
This is being actively worked on in #433

**Comment by kaizencc** [comment] 2022-07-22 15:29
Closing as a duplicate of #431

**Closed by kaizencc** 2022-07-22 15:29 UTC
Labels: management/tracking, status/proposed
