### ISSUE TITLE
Construct library graduation process

### ISSUE THREAD

**Issue by eladb** [aws/aws-cdk-rfcs#28] opened 2019-12-09 02:35 UTC
|PR|Champion|
|--|--------|
|# |        |

## Description

Devise a methodology to graduate a module

- Bake time (age)
- Bugs
- Feature-set
- API sign-off
- Documentation
- Sample
- Bug Bash
- Usability

Devise a metric of "amount" of experimentation we have, and track it so we allocate capacity to maintain continuously.

## Progress

- [x] Tracking Issue Created
- [ ] RFC PR Created 
- [ ] Core Team Member Assigned 
- [ ] Initial Approval / Final Comment Period
- [ ] Ready For Implementation
    
    - [ ] implementation issue 1
- [ ] Resolved

**Comment by ccfife** [comment] 2020-02-24 19:29
Closing because this is a duplicate of: https://github.com/aws/aws-cdk-rfcs/issues/107

**Closed by ccfife** 2020-02-24 19:29 UTC
Labels: process, status/proposed
